"""
Vantedge - Bet9ja API Structure Documentation
Generated by clean-code-agent

This script documents the "PalimpsestAjax/GetEventsInGroupV2" response structure
and maps the "O" (Odds) keys to their market meanings based on live verification.
"""

import json

# The "O" (Outcome) dictionary structure from Bet9ja V2 API:
BET9JA_ODDS_MAPPING = {
    # 1X2 (Match Winner)
    "S_1X2_1": "Home Win",
    "S_1X2_X": "Draw",
    "S_1X2_2": "Away Win",

    # Double Chance
    "S_DC_1X": "Home/Draw",
    "S_DC_12": "Home/Away",
    "S_DC_X2": "Draw/Away",

    # Over/Under 2.5 (Most common)
    "S_OU@2.5_O": "Over 2.5",
    "S_OU@2.5_U": "Under 2.5",
    
    # Generic Over/Under Pattern: S_OU@[LINE]_[O/U]
    # Examples:
    "S_OU@0.5_O": "Over 0.5",
    "S_OU@0.5_U": "Under 0.5",
    "S_OU@1.5_O": "Over 1.5",
    "S_OU@1.5_U": "Under 1.5",
    "S_OU@3.5_O": "Over 3.5",
    "S_OU@3.5_U": "Under 3.5",

    # GG/NG (Both Teams to Score)
    "S_GGNG_Y": "Yes (GG)",
    "S_GGNG_N": "No (NG)",

    # 1st Half 1X2
    "S_1X21_11": "1st Half Home",
    "S_1X21_X1": "1st Half Draw",
    "S_1X21_21": "1st Half Away",

    # 2nd Half 1X2
    "S_1X22_12": "2nd Half Home",
    "S_1X22_X2": "2nd Half Draw",
    "S_1X22_22": "2nd Half Away",

    # 1st Half Double Chance
    "S_DC1T_1X": "1st Half Home/Draw",
    "S_DC1T_12": "1st Half Home/Away",
    "S_DC1T_X2": "1st Half Draw/Away",
    
    # Odd/Even
    "S_OE_OD": "Odd",
    "S_OE_EV": "Even"
}

def parse_bet9ja_odds(odds_dict):
    """
    Parses the 'O' dictionary from Bet9ja response into a clean format.
    """
    parsed = {}
    
    # Standard 1X2
    if "S_1X2_1" in odds_dict:
        parsed["1x2"] = {
            "home": float(odds_dict["S_1X2_1"]),
            "draw": float(odds_dict["S_1X2_X"]),
            "away": float(odds_dict["S_1X2_2"])
        }
    
    # Over/Under 2.5
    if "S_OU@2.5_O" in odds_dict:
        parsed["ou_2.5"] = {
            "over": float(odds_dict["S_OU@2.5_O"]),
            "under": float(odds_dict["S_OU@2.5_U"])
        }
        
    # GG/NG
    if "S_GGNG_Y" in odds_dict:
        parsed["gg_ng"] = {
            "yes": float(odds_dict["S_GGNG_Y"]),
            "no": float(odds_dict["S_GGNG_N"])
        }
        
    return parsed

# Example usage with the data payload structure found:
# event = data['D']['E'][0]
# odds = event['O']
# clean_odds = parse_bet9ja_odds(odds)
