-- Seed sample value opportunities for testing
-- Run this after migrations to populate test data

-- First, insert some sample odds snapshots
INSERT INTO odds_snapshots (match_id, match_name, sport, league, kickoff_time, bookmaker, market, selection, odds, is_sharp) VALUES
-- Match 1: Arsenal vs Chelsea
('arsenal_vs_chelsea_2026-01-20', 'Arsenal vs Chelsea', 'football', 'Premier League', '2026-01-20 15:00:00+00', 'pinnacle', '1X2', 'Arsenal', 1.85, true),
('arsenal_vs_chelsea_2026-01-20', 'Arsenal vs Chelsea', 'football', 'Premier League', '2026-01-20 15:00:00+00', 'bet9ja', '1X2', 'Arsenal', 2.10, false),
('arsenal_vs_chelsea_2026-01-20', 'Arsenal vs Chelsea', 'football', 'Premier League', '2026-01-20 15:00:00+00', 'sportybet', '1X2', 'Arsenal', 2.05, false),
('arsenal_vs_chelsea_2026-01-20', 'Arsenal vs Chelsea', 'football', 'Premier League', '2026-01-20 15:00:00+00', 'pinnacle', 'Over/Under 2.5', 'Over 2.5', 1.95, true),
('arsenal_vs_chelsea_2026-01-20', 'Arsenal vs Chelsea', 'football', 'Premier League', '2026-01-20 15:00:00+00', 'bet9ja', 'Over/Under 2.5', 'Over 2.5', 2.20, false),

-- Match 2: Man City vs Liverpool
('man_city_vs_liverpool_2026-01-21', 'Man City vs Liverpool', 'football', 'Premier League', '2026-01-21 17:30:00+00', 'pinnacle', '1X2', 'Man City', 1.75, true),
('man_city_vs_liverpool_2026-01-21', 'Man City vs Liverpool', 'football', 'Premier League', '2026-01-21 17:30:00+00', 'betking', '1X2', 'Man City', 1.95, false),
('man_city_vs_liverpool_2026-01-21', 'Man City vs Liverpool', 'football', 'Premier League', '2026-01-21 17:30:00+00', 'bet9ja', '1X2', 'Man City', 1.92, false),
('man_city_vs_liverpool_2026-01-21', 'Man City vs Liverpool', 'football', 'Premier League', '2026-01-21 17:30:00+00', 'pinnacle', 'Both Teams to Score', 'Yes', 1.80, true),
('man_city_vs_liverpool_2026-01-21', 'Man City vs Liverpool', 'football', 'Premier League', '2026-01-21 17:30:00+00', 'sportybet', 'Both Teams to Score', 'Yes', 2.05, false),

-- Match 3: Real Madrid vs Barcelona
('real_madrid_vs_barcelona_2026-01-22', 'Real Madrid vs Barcelona', 'football', 'La Liga', '2026-01-22 20:00:00+00', 'pinnacle', '1X2', 'Real Madrid', 2.10, true),
('real_madrid_vs_barcelona_2026-01-22', 'Real Madrid vs Barcelona', 'football', 'La Liga', '2026-01-22 20:00:00+00', 'bet9ja', '1X2', 'Real Madrid', 2.45, false),
('real_madrid_vs_barcelona_2026-01-22', 'Real Madrid vs Barcelona', 'football', 'La Liga', '2026-01-22 20:00:00+00', 'pinnacle', 'Over/Under 3.5', 'Over 3.5', 2.25, true),
('real_madrid_vs_barcelona_2026-01-22', 'Real Madrid vs Barcelona', 'football', 'La Liga', '2026-01-22 20:00:00+00', 'betking', 'Over/Under 3.5', 'Over 3.5', 2.60, false),

-- Match 4: Lakers vs Warriors (Basketball)
('lakers_vs_warriors_2026-01-20', 'Lakers vs Warriors', 'basketball', 'NBA', '2026-01-20 02:00:00+00', 'pinnacle', 'Moneyline', 'Lakers', 1.90, true),
('lakers_vs_warriors_2026-01-20', 'Lakers vs Warriors', 'basketball', 'NBA', '2026-01-20 02:00:00+00', 'bet9ja', 'Moneyline', 'Lakers', 2.15, false);

-- Now insert value opportunities (these would normally be auto-generated by detect_value_opportunities function)
INSERT INTO value_opportunities (
  match_id, match_name, sport, league, kickoff_time, market, selection,
  sharp_bookmaker, sharp_odds, soft_bookmaker, soft_odds, edge_percent, kelly_fraction, status
) VALUES
-- Arsenal vs Chelsea - 1X2 Arsenal
('arsenal_vs_chelsea_2026-01-20', 'Arsenal vs Chelsea', 'football', 'Premier League', '2026-01-20 15:00:00+00',
 '1X2', 'Arsenal', 'pinnacle', 1.85, 'bet9ja', 2.10, 13.51, 0.0338, 'active'),

-- Arsenal vs Chelsea - Over 2.5
('arsenal_vs_chelsea_2026-01-20', 'Arsenal vs Chelsea', 'football', 'Premier League', '2026-01-20 15:00:00+00',
 'Over/Under 2.5', 'Over 2.5', 'pinnacle', 1.95, 'bet9ja', 2.20, 12.82, 0.0321, 'active'),

-- Man City vs Liverpool - 1X2 Man City
('man_city_vs_liverpool_2026-01-21', 'Man City vs Liverpool', 'football', 'Premier League', '2026-01-21 17:30:00+00',
 '1X2', 'Man City', 'pinnacle', 1.75, 'betking', 1.95, 11.43, 0.0286, 'active'),

-- Man City vs Liverpool - BTTS Yes
('man_city_vs_liverpool_2026-01-21', 'Man City vs Liverpool', 'football', 'Premier League', '2026-01-21 17:30:00+00',
 'Both Teams to Score', 'Yes', 'pinnacle', 1.80, 'sportybet', 2.05, 13.89, 0.0347, 'active'),

-- Real Madrid vs Barcelona - 1X2 Real Madrid (High Edge!)
('real_madrid_vs_barcelona_2026-01-22', 'Real Madrid vs Barcelona', 'football', 'La Liga', '2026-01-22 20:00:00+00',
 '1X2', 'Real Madrid', 'pinnacle', 2.10, 'bet9ja', 2.45, 16.67, 0.0417, 'active'),

-- Real Madrid vs Barcelona - Over 3.5
('real_madrid_vs_barcelona_2026-01-22', 'Real Madrid vs Barcelona', 'football', 'La Liga', '2026-01-22 20:00:00+00',
 'Over/Under 3.5', 'Over 3.5', 'pinnacle', 2.25, 'betking', 2.60, 15.56, 0.0389, 'active'),

-- Lakers vs Warriors - Moneyline Lakers
('lakers_vs_warriors_2026-01-20', 'Lakers vs Warriors', 'basketball', 'NBA', '2026-01-20 02:00:00+00',
 'Moneyline', 'Lakers', 'pinnacle', 1.90, 'bet9ja', 2.15, 13.16, 0.0329, 'active');

-- Verify data
SELECT 
  match_name,
  market,
  selection,
  soft_bookmaker,
  soft_odds,
  edge_percent,
  status
FROM value_opportunities
WHERE status = 'active'
ORDER BY edge_percent DESC;
